### ISSUE TITLE
cloudci plugin not available

### ISSUE THREAD

**Issue by dkwakkel** [ysb33r/gradle-cloudci-plugin#2]
Hi, we are using your plugin. But noticed it is not possible to download. I followed the urls and the url at repo.jfrog.org is not working: 

```
curl -v https://plugins.gradle.org/m2/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.jar
 2015  curl -v https://jcenter.bintray.com/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.jar
 2016  curl -v https://repo.jfrog.org/artifactory/libs-release-bintray/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.jar?referrer
```

Same for 2.2 version. Is it possible to fix this?

**Comment by ysb33r** [comment]
Wow. You are right. The JARs seem to be missing from that plugin and a number of others. I'll investigate.

**Comment by astellingwerf** [comment]
@dkwakkel , there's no need for a JAR there: There's a POM file that declares a dependency on another JAR that contains the actual implementation of this plugin.
I'm not entirely sure why that route was taken (I'd hope @ysb33r knows), but the approach should work...

**Comment by ysb33r** [comment]
I am now a bit more awake that when I answered that earlier:

For this this simple `build.gradle`:

```groovy
plugins {
  id 'org.ysb33r.cloudci' version "2.3"
}
```

and running:

```
$ gradle --refresh-dependencies --info tasks
```

the reduced output is:

```
...
Found locally available resource with matching checksum: [https://plugins.gradle.org/m2/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.pom, .../org.ysb33r.cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/867ad1bec81b59dbe59c429f1e4d9072fd232cd8/org.ysb33r.cloudci.gradle.plugin-2.3.pom]

Resource missing. [HTTP HEAD: https://plugins.gradle.org/m2/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.jar]
...
Download https://plugins.gradle.org/m2/gradle/plugin/org/ysb33r/gradle/gradle-cloudci-plugin/2.3/gradle-cloudci-plugin-2.3.pom
...
Download https://plugins.gradle.org/m2/gradle/plugin/org/ysb33r/gradle/gradle-cloudci-plugin/2.3/gradle-cloudci-plugin-2.3.jar
...
```

Notice the difference between where the POM is found and the artifact:

* `https://plugins.gradle.org/m2/org/ysb33r/cloudci/org.ysb33r.cloudci.gradle.plugin/2.3/org.ysb33r.cloudci.gradle.plugin-2.3.pom`
* `https://plugins.gradle.org/m2/gradle/plugin/org/ysb33r/gradle/gradle-cloudci-plugin/2.3/gradle-cloudci-plugin-2.3.jar`

This is something very specific to the Gradle plugin portal. I am not privvy to the reasons why the Gradle team decided to do it this way.

**Comment by ysb33r** [comment]
@dkwakkel Did you ever get your issue resolved?

**Comment by dkwakkel** [comment]
yes, you can close this ticket.

Op vr 15 mrt. 2019 om 23:34 schreef Schalk W. Cronjé <
notifications@github.com>:
